export const mockData = [
  {
    id: 1,
    trackingId: "SHP001234",
    origin: "Mumbai",
    destination: "Delhi",
    status: "In Transit",
    date: "2024-12-01",
    weight: "2.5kg",
  },
  {
    id: 2,
    trackingId: "SHP001235",
    origin: "Bangalore",
    destination: "Hyderabad",
    status: "Delivered",
    date: "2024-11-28",
    weight: "1.2kg",
  },
  {
    id: 3,
    trackingId: "SHP001236",
    origin: "Delhi",
    destination: "Pune",
    status: "Pending",
    date: "2024-12-02",
    weight: "3.8kg",
  },
  {
    id: 4,
    trackingId: "SHP001237",
    origin: "Chennai",
    destination: "Kolkata",
    status: "In Transit",
    date: "2024-12-01",
    weight: "5.0kg",
  },
  {
    id: 5,
    trackingId: "SHP001238",
    origin: "Pune",
    destination: "Mumbai",
    status: "Delivered",
    date: "2024-11-30",
    weight: "0.8kg",
  },
  {
    id: 6,
    trackingId: "SHP001239",
    origin: "Hyderabad",
    destination: "Bangalore",
    status: "In Transit",
    date: "2024-12-03",
    weight: "2.1kg",
  },
  {
    id: 7,
    trackingId: "SHP001240",
    origin: "Kolkata",
    destination: "Chennai",
    status: "Pending",
    date: "2024-12-03",
    weight: "4.5kg",
  },
  {
    id: 8,
    trackingId: "SHP001241",
    origin: "Delhi",
    destination: "Mumbai",
    status: "Delivered",
    date: "2024-11-29",
    weight: "1.9kg",
  },
  {
    id: 9,
    trackingId: "SHP001241",
    origin: "Kolkata",
    destination: "Mumbai",
    status: "Delivered",
    date: "2024-11-29",
    weight: "1.1kg",
  },
  {
    id: 10,
    trackingId: "SHP001241",
    origin: "Goa",
    destination: "Darjeeling",
    status: "Delivered",
    date: "2024-11-29",
    weight: "12.9kg",
  },
];
